import { Gabarito } from '@next/font/google'
import './globals.css'
import Nav from './components/Header'
import { ContainerContextProvider } from './store/container-ctx'
import localFont from '@next/font/local'
import { FontsContextProvider } from './store/fonts-ctx'
import { AnimationContextProvider } from './store/animation-ctx'
import { RouterContextProvider } from './store/router-ctx'
import TestPage from './test/page.jsx'
import PageTransitionBackground from './components/PageTransitionBackground'

const gabarito = Gabarito({ subsets: ['latin'] })
const akira = localFont({
  src: [
    {
      path: '../public/fonts/Akira-Expanded-Demo.otf',
      weight: '400',
    },
  ],
  variable: '--font-akira',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${akira.className} overflow-x-hidden`}>
        <ContainerContextProvider>
          <FontsContextProvider>
            <AnimationContextProvider>
              <RouterContextProvider>
                <Nav gabarito={gabarito} akira={akira} />
                <main>{children}</main>
                {/* <PageTransitionBackground /> */}
              </RouterContextProvider>
            </AnimationContextProvider>
          </FontsContextProvider>
        </ContainerContextProvider>
      </body>
    </html>
  )
}
